### ISSUE TITLE
Android Problem with decimal numbers

### ISSUE THREAD

**Issue by marcelamsler** [AlejandroRuiz/PayPal.Forms#1]
If I use a real decimal number like new Decimal(12.55) it throws an Error in Android Native Code. It happens only on Android 6.0. With Android 4.4.4 and IOS it works like Charm.

```
 Java.lang.NumberFormatException was thrown
Invalid long: "12,55"
```

Here is the complete Stacktrace:

```
Java.Lang.NumberFormatException: Invalid long: "12,55"
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
  at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (IntPtr jobject, IntPtr jclass, IntPtr jmethod, Android.Runtime.JValue* parms) [0x00084] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:1029
  at Android.Runtime.JNIEnv.FinishCreateInstance (IntPtr instance, IntPtr jclass, IntPtr constructorId, Android.Runtime.JValue* constructorParameters) [0x0000b] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.cs:306
  at Java.Math.BigDecimal..ctor (System.String val) [0x000cc] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Math.BigDecimal.cs:401
  at PayPal.Forms.PayPalManager.BuyItem (PayPal.Forms.Abstractions.PayPalItem item, Decimal xftax, System.Action onCancelled, System.Action`1 onSuccess, System.Action`1 onError, PayPal.Forms.Abstractions.ShippingAddress address) [0x0002b] in <filename unknown>:0
  at PayPal.Forms.PayPalManagerImplementation.Buy (PayPal.Forms.Abstractions.PayPalItem item, Decimal tax, PayPal.Forms.Abstractions.ShippingAddress address) [0x00034] in <filename unknown>:0
  at customerapp.ProductListPage+<OnOrderButtonClick>c__async0.MoveNext () [0x000e3] in /Users/marcelamsler/Projects/project-helin/customer-app/ProductListPage.xaml.cs:55
  at --- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:994
  at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:18
  at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
  at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.IRunnable.cs:71
  at at (wrapper dynamic-method) System.Object:6e5adf81-bdd7-43d9-a846-1fab649a4304 (intptr,intptr)
  at --- End of managed exception stack trace ---
  at java.lang.NumberFormatException: Invalid long: "12,55"
  at at java.lang.Long.invalidLong(Long.java:124)
  at at java.lang.Long.parse(Long.java:363)
  at at java.lang.Long.parseLong(Long.java:353)
  at at java.lang.Long.parseLong(Long.java:321)
  at at java.math.BigDecimal.<init>(BigDecimal.java:344)
  at at java.math.BigDecimal.<init>(BigDecimal.java:425)
  at at android.support.v7.app.AlertDialog_IDialogInterfaceOnClickListenerImplementor.n_onClick(Native Method)
  at at android.support.v7.app.AlertDialog_IDialogInterfaceOnClickListenerImplementor.onClick(AlertDialog_IDialogInterfaceOnClickListenerImplementor.java:29)
  at at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
  at at android.os.Handler.dispatchMessage(Handler.java:102)
  at at android.os.Looper.loop(Looper.java:150)
  at at android.app.ActivityThread.main(ActivityThread.java:5546)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)`
```

**Comment by AlejandroRuiz** [comment]
@marcelamsler please take a look to this release and let me know if it solve this issue https://www.nuget.org/packages/PayPal.Forms/2.0.3
